services:
  keycloak-db:
    image: postgres:17-alpine
    container_name: keycloak-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-change_me_strong}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s   

  keycloak:
    image: quay.io/keycloak/keycloak:26.0    
    container_name: idp-keycloak
    restart: unless-stopped
    command: start-dev   
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin_strong}
      # Keycloakify cache disable (dev)
      KC_SPI_THEME_STATIC_MAX_AGE: -1
      KC_SPI_THEME_CACHE_THEMES: false
      KC_SPI_THEME_CACHE_TEMPLATES: false
    depends_on:
      keycloak-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/9000 && printf 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q UP"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics" , "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s 

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_ADMIN_PASSWORD:-seq_strong}
    healthcheck:
      test: ["CMD", "curl" , "-f" ,"http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s 
    volumes:
      - seq_data:/data

  product-db:
    image: postgres:17-alpine
    container_name: product-db
    restart: unless-stopped
    env_file:
      - ./services/product/.env
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: product
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD:-change_me_strong}
    volumes:
      - product_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product -d product"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s   

  order-db:
    image: postgres:17-alpine
    container_name: order-db
    restart: unless-stopped
    env_file:
      - ./services/order/.env
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: order
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD:-change_me_strong}
    volumes:
      - order_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order -d order"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s  

  notification-db:
    image: postgres:17-alpine
    container_name: notification-db
    restart: unless-stopped
    env_file:
      -  ./services/notification/.env
    environment:
      POSTGRES_DB: notification
      POSTGRES_USER: notification
      POSTGRES_PASSWORD: ${NOTIFICATION_DB_PASSWORD:-change_me_strong}
    volumes:
      - notification_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification -d notification"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s 

  gateway:
    image: getway:latest
    container_name: gateway
    restart: unless-stopped  
    depends_on:
      keycloak:
        condition: service_healthy
      keycloak-db: 
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      product-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7000
      - ConnectionStrings__Default=Host=keycloak-db;Port=5432;Database=keycloak;Username=keycloak;Password=${KEYCLOAK_DB_PASSWORD}
      - Keycloak__Authority=http://keycloak:8080/realms/Core 
    healthcheck:
      test: ["CMD", "curl" , "-f" ,"http://localhost:7000/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  product-service:
    image: product-service:latest
    container_name: product-service
    restart: unless-stopped
    env_file:
      - ./services/product/.env
    depends_on:
      product-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      seq:
         condition: service_healthy
    healthcheck:
      test: ["CMD", "curl" , "-f" ,"http://localhost:7002/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  order-service:
    image: order-service:latest
    container_name: order-service
    restart: unless-stopped
    env_file:
      - ./services/order/.env
    depends_on:
      order-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      seq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl" , "-f" ,"http://localhost:7003/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s 

  notification-service:
    image: notification-service:latest
    container_name: notification-service
    restart: unless-stopped
    env_file:
      - ./services/notification/.env
    depends_on:
      notification-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      seq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl" , "-f" ,"http://localhost:7004/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  keycloak_data:
  product_data:
  order_data:
  notification_data:
  seq_data: